// Centralized Portfolio Data for Ankit Sharma
const PORTFOLIO_DATA = {
  personal: {
    name: "Ankit Sharma",
    age: 20,
    location: "Jaipur, Rajasthan, India",
    displayLocation: "Jaipur, India",
    college: "Jaipur Engineering & Research Centre (JECRC), Jaipur",
    degree: "Bachelor of Technology in Computer Science",
    year: "3rd Year",
    graduation: "July 2028",
    cgpa: "8.5/10",
    school: "Children's Academy Group, Alwar",
    schoolPeriod: "2022 – 2024",
    class12: "92%",
    class10: "95.83%",
  },
  contact: {
    phone: "+91 9784508927",
    email: "ankitproff18@gmail.com",
    github: "https://github.com/ashfed18yes",
    linkedin: "https://linkedin.com/in/ankitsharma",
  },
  hero: {
    headline: "Hi, I'm Ankit Sharma.",
    subheading: "I build software, websites and digital experiences.",
  },
  about: {
    paragraph1: "I'm Ankit Sharma, a third-year Computer Science student at Jaipur Engineering & Research Centre (JECRC), Jaipur. I enjoy building practical software, websites and digital experiences while exploring both the technical and creative sides of technology.",
    paragraph2: "Alongside my academics, I've worked on freelance and real-world projects involving web development, graphic design, video editing, content management, social media management and automation.",
    paragraph3: "I enjoy turning ideas into working solutions — from websites and mobile applications to digital workflows and creative projects.",
  },
  skills: [
    { name: "Web Development", width: "88%" },
    { name: "Backend & Java", width: "82%" },
    { name: "Mobile & Android", width: "78%" },
    { name: "Core CS & DSA", width: "80%" },
    { name: "Creative & Digital", width: "85%" },
  ],
  experience: [
    {
      role: "Web Developer Intern",
      company: "Truetalk",
      period: "October 2025 – December 2025",
      website: "https://truetalk.co.in",
      description: "Contributed to the development of a mental health platform connecting users with therapists. Improved website usability and accessibility to enhance the user experience.",
    },
    {
      role: "Chief Technical Officer (CTO)",
      company: "JECRC Incubation Centre",
      period: "March 2026",
      description: "Led technical strategy and coordinated development teams across startup-focused projects. Drove execution of multiple technology initiatives from planning to implementation.",
    },
    {
      role: "Execution Head",
      company: "PRISM",
      period: "February 2026 – March 2026",
      description: "Executed a technology-driven initiative focused on solving real-world problems within the college.",
    },
  ],
  projects: [
    {
      id: 0,
      name: "Event Expense Management App",
      category: "Mobile Application / Event Finance",
      organization: "JECRC Incubation Centre",
      period: "March 2026",
      description: "Built a mobile application for event expense tracking and financial transparency. Implemented Firebase-based real-time data synchronization for event expense records.",
      image: "images/projects/krushigram.png",
      tags: ["android", "kotlin", "firebase", "mobile"],
      liveview: "https://github.com/ashfed18yes",
      alt: "Event Expense Management App",
    },
    {
      id: 1,
      name: "Balaji Tiles",
      category: "Business Website / Web Development",
      description: "A business website developed for Balaji Tiles to establish and present its digital presence.",
      image: "images/projects/theiqic.jpeg",
      tags: ["webdev", "frontend", "business"],
      liveview: "https://balajitiles.com",
      alt: "Balaji Tiles Website",
    },
    {
      id: 2,
      name: "Pooja Speech & Hearing Clinic",
      category: "Healthcare Website / Web Development",
      description: "A professional website developed for Pooja Speech & Hearing Clinic to present its services and online presence.",
      image: "images/projects/marketing-agency.png",
      tags: ["webdev", "frontend", "healthcare"],
      liveview: "https://poojaspeechandhearing.in",
      alt: "Pooja Speech & Hearing Clinic Website",
    },
    {
      id: 3,
      name: "JIC Foundation",
      category: "Organization Website / Web Development",
      description: "A website developed for JIC Foundation to showcase its initiatives and online presence.",
      image: "images/projects/projecthub.png",
      tags: ["webdev", "frontend", "organization"],
      liveview: "https://jicfoundation.co.in",
      alt: "JIC Foundation Website",
    },
    {
      id: 4,
      name: "RKK Constructions",
      category: "Business Website / Web Development",
      description: "A professional website developed for RKK Constructions.",
      image: "images/projects/coffee.jpg",
      tags: ["webdev", "frontend", "business"],
      liveview: "https://rkkconstructions.com",
      alt: "RKK Constructions Website",
    },
    {
      id: 5,
      name: "JECRC Entrepreneur Challenge",
      category: "Event / Entrepreneurship Website",
      description: "A website developed for the JECRC Entrepreneur Challenge to support its digital presence and event communication.",
      image: "images/projects/randomizer.jpg",
      tags: ["webdev", "event"],
      liveview: "https://jecrentrepreneurchallenge.co.in",
      alt: "JECRC Entrepreneur Challenge Website",
    },
    {
      id: 6,
      name: "Prozify",
      category: "Business / Digital Platform",
      description: "A web project developed as part of my freelance and digital development work.",
      image: "images/projects/vaporui.jpeg",
      tags: ["webdev", "digital"],
      liveview: "https://prozify.com",
      alt: "Prozify Digital Platform",
    },
    {
      id: 7,
      name: "Truetalk",
      category: "Web Development",
      description: "A website I worked on during my Web Developer Internship at Truetalk.",
      image: "images/projects/studybuddy.jpeg",
      tags: ["webdev", "internship"],
      liveview: "https://truetalk.co.in",
      alt: "Truetalk Website",
    },
    {
      id: 8,
      name: "Aryan Tech",
      category: "Web Development",
      description: "A web development project created as part of my practical development work.",
      image: "images/projects/opentalk.jpeg",
      tags: ["webdev", "frontend"],
      liveview: "https://aryantech.vercel.app",
      alt: "Aryan Tech Website",
    },
  ],
};

if (typeof window !== "undefined") {
  window.PORTFOLIO_DATA = PORTFOLIO_DATA;
}
if (typeof module !== "undefined" && module.exports) {
  module.exports = PORTFOLIO_DATA;
}
